title: My Awesome Site
description: This is my awesome site.
baseurl: "/my-awesome-site"
url: "https://example.com"

theme: jekyll-theme-primer

plugins:
  - jekyll-feed

exclude:
  - README.md

sass:
  sass_dir: _sass
  style: compressed
