[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[headers]]
  for = "/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
