name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    with:
      repository: ParadiseMan900/stupidWebPython
      path: flaskappGit

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Run web app
      run: python some_app.py &
      background: true

    - name: Wait for web app to start
      run: |
        sleep 5
        curl http://localhost:5000
